"""optimized the tables

Revision ID: 056e0be8fed3
Revises: e36297eb0c9a
Create Date: 2025-09-28 12:09:01.495334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '056e0be8fed3'
down_revision: Union[str, Sequence[str], None] = 'e36297eb0c9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploaded_files', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('uploaded_files', sa.Column('guest_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'uploaded_files', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'uploaded_files', type_='foreignkey')
    op.drop_column('uploaded_files', 'guest_id')
    op.drop_column('uploaded_files', 'user_id')
    # ### end Alembic commands ###
