"""Add guest_id foreign key to uploaded_files

Revision ID: 0fc9a90c1103
Revises: 9b324260e60c
Create Date: 2025-09-30 11:26:29.354628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fc9a90c1103'
down_revision: Union[str, Sequence[str], None] = '9b324260e60c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
