"""Fix guest_id type to UUID

Revision ID: 3f4633b8125a
Revises: e96b50e8b1d9
Create Date: 2025-09-30 12:01:08.898026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f4633b8125a'
down_revision: Union[str, Sequence[str], None] = 'e96b50e8b1d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploaded_files', sa.Column('guest_id', sa.UUID(as_uuid=False), nullable=True))
    op.create_foreign_key(None, 'uploaded_files', 'guests', ['guest_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'uploaded_files', type_='foreignkey')
    op.drop_column('uploaded_files', 'guest_id')
    # ### end Alembic commands ###
