"""Add guest_id foreign key to uploaded_files

Revision ID: ab5d0841bcd1
Revises: 0fc9a90c1103
Create Date: 2025-09-30 11:34:56.990236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab5d0841bcd1'
down_revision: Union[str, Sequence[str], None] = '0fc9a90c1103'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'uploaded_files', 'guests', ['guest_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'uploaded_files', type_='foreignkey')
    # ### end Alembic commands ###
