"""whatsapp template table added

Revision ID: cf60b20ea4e4
Revises: c3fc15ca2157
Create Date: 2025-10-11 09:18:56.991518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf60b20ea4e4'
down_revision: Union[str, Sequence[str], None] = 'c3fc15ca2157'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
