name: FastAPI CI/CD

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: [self-hosted]

    steps:
    # 1️⃣ Checkout code
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2️⃣ Ensure Docker is running
    - name: Check Docker
      run: |
        docker --version
        docker compose version

    # 3️⃣ Set environment variables for Docker Compose
    - name: Export env variables
      run: |
        echo "PG_PASSWORD=harif313" >> $GITHUB_ENV
        # You can add more variables here if needed

    # 4️⃣ Bring down any previous containers (safe for first run)
    - name: Stop previous containers
      run: docker compose down

    # 5️⃣ Build and start containers
    - name: Build and start containers
      run: docker compose up -d --build

    # 6️⃣ Wait for backend to be healthy
    - name: Wait for backend
      run: |
        echo "Waiting for backend to be ready..."
        until docker compose exec backend curl -s http://localhost:8000/health >/dev/null 2>&1; do
          sleep 3
        done

    # 7️⃣ Run backend tests
    - name: Run backend tests
      run: docker compose exec backend pytest app/tests
