name: fastapi CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: [self-hosted]

    steps:
    # 1️⃣ Fix workspace permissions before checkout
    - name: Fix workspace permissions
      run: sudo chown -R $USER:$USER $GITHUB_WORKSPACE

    # 2️⃣ Checkout code
    - name: Checkout repository
      uses: actions/checkout@v4

    # 3️⃣ Clean up any lingering __pycache__ files
    - name: Remove old pycache
      run: find $GITHUB_WORKSPACE -name "__pycache__" -type d -exec rm -rf {} +

    # 4️⃣ Ensure Docker is running
    - name: Check Docker
      run: |
        docker --version
        docker compose version

    # 5️⃣ Export environment variables for Docker Compose
    - name: Set environment variables
      run: |
        export PG_PASSWORD=harif313
        # Add any other env vars here if needed

    # 6️⃣ Bring down any existing containers
    - name: Stop previous containers
      run: docker compose down

    # 7️⃣ Build and start Docker containers
    - name: Build and start containers
      run: docker compose up -d --build

    # 8️⃣ Wait for backend to be ready
    - name: Wait for backend
      run: |
        echo "Waiting for backend to be ready..."
        until docker compose exec backend curl -s http://localhost:8000/health; do
          sleep 3
        done

    # 9️⃣ Optional: Run backend tests
    - name: Run backend tests
      run: docker compose exec backend pytest app/tests
