name: fastapi CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: [self-hosted]

    steps:
    # 1️⃣ Checkout code
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2️⃣ Clean pycache (optional if gitignore exists)
    - name: Remove old pycache
      run: find $GITHUB_WORKSPACE -name "__pycache__" -type d -exec rm -rf {} +

    # 3️⃣ Ensure Docker is running
    - name: Check Docker
      run: |
        docker --version
        docker compose version

    # 4️⃣ Export environment variables
    - name: Set environment variables
      run: |
        export PG_PASSWORD=harif313

    # 5️⃣ Bring down any previous containers
    - name: Stop previous containers
      run: docker compose down

    # 6️⃣ Build and start containers
    - name: Build and start containers
      run: docker compose up -d --build

    # 7️⃣ Wait for backend to be ready
    - name: Wait for backend
      run: |
        echo "Waiting for backend to be ready..."
        until docker compose exec backend curl -s http://localhost:8000/health; do
          sleep 3
        done

    # 8️⃣ Run backend tests
    - name: Run backend tests
      run: docker compose exec backend pytest app/tests
