name: FastAPI CI/CD

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: [self-hosted]

    steps:

      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Ensure Docker is available
      - name: Check Docker
        run: |
          docker --version
          docker compose version

      # 3️⃣ Stop any previous containers safely
      - name: Stop previous containers
        run: |
          if [ -f docker-compose.yml ]; then
            docker compose --env-file /home/env/sucrm.env down || true
          fi

      # 4️⃣ Build and start containers
      - name: Build and start containers
        run: docker compose --env-file /home/env/sucrm.env up -d --build

      # 5️⃣ Wait for backend to be healthy
      - name: Wait for backend
        run: |
          timeout=60
          count=0
          until docker compose --env-file /home/env/sucrm.env run --rm backend curl -s http://0.0.0.0:8000/health >/dev/null 2>&1; do
            sleep 3
            count=$((count+3))
            if [ $count -ge $timeout ]; then
              echo "Backend did not become healthy in $timeout seconds"
              docker compose --env-file /home/env/sucrm.env logs backend --tail 50
              exit 1
            fi
          done

      # 6️⃣ Run backend tests
      - name: Run backend tests
        run: docker compose --env-file /home/env/sucrm.env run --rm backend pytest app/tests
