name: fastapi CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: [self-hosted]
    steps:
    - uses: actions/checkout@v4
    - name: install dependencies
      run: |
        python3 -m venv venv
        source venv/bin/activate
        pip install -r backend/requirements.txt
    
