name: FastAPI CI/CD

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: [self-hosted]

    steps:

      - name: Remove Python cache
        run: find /home/harif/actions-runner/_work/sucrm -type d -name "__pycache__" -exec rm -rf {} +

      - name: Fix permissions (ignore errors)
        run: chown -R harif:harif /home/harif/actions-runner/_work/sucrm 2>/dev/null || true

      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Ensure Docker is available
      - name: Check Docker
        run: |
          docker --version
          docker compose version

      # 3️⃣ Stop any previous containers
      - name: Stop previous containers
        run: docker compose --env-file /home/env/sucrm.env down

      # 4️⃣ Build and start containers
      - name: Build and start containers
        run: docker compose --env-file /home/env/sucrm.env up -d --build

      # 5️⃣ Wait for backend to be healthy
      - name: Wait for backend
        run: |
          timeout=60
          count=0
          until docker compose --env-file /home/env/sucrm.env run --rm backend curl -s http://0.0.0.0:8000/health >/dev/null 2>&1; do
            sleep 3
            count=$((count+3))
            if [ $count -ge $timeout ]; then
              echo "Backend did not become healthy in $timeout seconds"
              docker compose --env-file /home/env/sucrm.env logs backend --tail 50
              exit 1
            fi
          done
          
      # 6️⃣ Run backend tests
      - name: Run backend tests
        run: docker compose --env-file /home/env/sucrm.env run --rm backend pytest app/tests

